### ISSUE TITLE
css class names containing '-' can only be parsed via dict

### ISSUE THREAD

**Issue by stchris** [jessemiller/HamlPy#10]
I'm trying to work with HamlPy and blueprint-css. For the latter I need css class names like 'span-24'. When I write the following HamlPy markup:
    .header.span-24.last
I get:
    <div class='header span'>-24.last</div>

My curent workaround is:
    .header.last{'class':'span-24'}
which yields the expected result
    <div class='header last span-24'>

The other acceptable solution
    %div{'class':('header', 'last', 'span-24')} 
doesn't work because of Issue #9

**Comment by jessemiller** [comment]
This is also fixed now.. again thanks for the input.
