### ISSUE TITLE
HamlPyExtension filename extension check invalid

### ISSUE THREAD

**Issue by aydinyanik** [jessemiller/HamlPy#114]
I noticed the "has_any_extension" function always returns true no matter what extension the files have.

``` python
def has_any_extension(file_path, extensions):
    file_ext = get_file_extension(file_path)
    return file_ext and extensions and [clean_extension(e) for e in extensions]
```

I think it's looking if the extensions in the HAML_FILE_NAME_EXTENSIONS list are in the same list, which always returns true.

Replacing  it with this fixes it.

``` python
def has_any_extension(file_path, extensions):
    file_ext = get_file_extension(file_path)
    return file_ext and file_ext and file_ext in extensions
```

**Comment by a-krebs** [comment]
Semantically, the function should return true if `file_path` is in `extensions`, as I understand.

Then shouldn't it be:

``` python
def has_any_extension(file_path, extensions):
    file_ext = get_file_extension(file_path)
    return file_ext and extensions and file_ext in [clean_extension(e) for e in extensions]
```

I'm thinking you intended the second `file_ext` in the return statement to be `extensions`, but we also still want to pass `extensions` through `clean_extension()`.
