### ISSUE TITLE
Loader mishandles file name extensions

### ISSUE THREAD

**Issue by a-krebs** [jessemiller/HamlPy#116]
When using the template loader for django, it will load templates that match on file name, but will mishandle file extensions.
For example, if the template file `template.hamlpy` exists, but the template to be loaded is `template.txt`, the hamlpy loader will load `template.hamlpy`, and ignore the file extension.

It looks like this is because in the loader class definition (`hamlpy.tempaltes.loaders`, below), we're looping over `hamlpy.VALID_EXTENSIONS` rather than checking `if _extension in hamlpy.VALID_EXTENSIONS`. I don't think we should be trying to load any template with a valid extension that matches on filename, which is what we're doing right now.

``` python
def load_template_source(self, template_name, *args, **kwargs):
    _name, _extension = os.path.splitext(template_name)

    for extension in hamlpy.VALID_EXTENSIONS:
        try:
            haml_source, template_path = super(Loader, self).load_template_source(
                self._generate_template_name(_name, extension), *args, **kwargs
            )
        except TemplateDoesNotExist:
            pass
        else:
            hamlParser = hamlpy.Compiler(options_dict=self._get_options_dict())
            html = hamlParser.process(haml_source)

            return html, template_path

    raise TemplateDoesNotExist(template_name)
```

**Comment by a-krebs** [comment]
I've added some tests to demonstrate this behavior.
I had to do some refactoring to decouple the loader from other django components as much as possible, since I didn't want to make these tests depend on an entire django environment.
As it stands hamlpy.template.**init** needed to be commented out to stop a dependency on django.config.settings.

If anyone knows a way to refactor this further or write the tests differently to work around importing django components any input would be appreciated. I'd like to have these tests included in hamlpy in such a way that they can run without needing a django environment or any commenting-out of code.

**Comment by jessemiller** [comment]
Thanks, I've pulled in that request. I think a good way to refactor would be to pull those extension helpers (clean_extension, get_file_extension, has_any_extension) into their own file so they can be tested independently.

**Comment by a-krebs** [comment]
This isn't the same as #114 and #115; those were regarding the jinja2 extensions.
The issue here is that the django template loader _also_ does something erroneous with file extensions, but it's something different than what was discussed in #114.

**Comment by a-krebs** [comment]
It looks like the [django documentation](https://docs.djangoproject.com/en/dev/topics/settings/#using-settings-without-setting-django-settings-module)  describes a way to decouple these tests from a django environment by configuring django settings manually:

``` python
from django.conf import settings

settings.configure(DEBUG=True, TEMPLATE_DEBUG=True)
```

I'll clean up the tests and open a different pull request with them and a fix.

**Comment by jessemiller** [comment]
Sorry about that. Good find on the django documentation. Thanks!
