### ISSUE TITLE
Automatic closing of script tags = not ideal

### ISSUE THREAD

**Issue by jjt** [jessemiller/HamlPy#12]
Right now there's no way to output the ever-so-standard
    <script src="my-cool-script.js"></script>

Since you have an explicit way to self-close the tag (/), it would be better to always close the tag in the standard way in the absence of that explicit slash.

**Comment by jessemiller** [comment]
I just went with the same defaults for autoclose as the original haml.  I'd like to add a configuration in soon where you'd be able to override those though.  I see for now you found in elements.py you can just remove 'script' from the self_closing_tags tuple.
