### ISSUE TITLE
An apostrophe ( ' ) in element attribute is always escaped

### ISSUE THREAD

**Issue by adrianzamorski** [jessemiller/HamlPy#125]
If you write:

``` haml
%div{ title: "It can't be removed" }
```

you'll get in the result

``` html
<div title="It can\" t="" be="" removed=""><div>
```

I tried many ways to bypass it.

Try to escape it by myself:

``` haml
%div{ title: 'It can\'t be removed' }
```

Use 'with' tag:

``` haml
- with "It can't be removed" as title_text
    %div{ title: "{{ title_text }}" }
```

Use 'autoescape off' tag:

``` haml
- autoescape off
    %div{ title: "It can't be removed" }
```

Define a context variable in a view:

``` python
context['title_text'] = "It can't be removed"
```

and use it in the template:

``` haml
%div{ title: "{{ title_text }}" }
```

I found that only the last one works and gives me correctly compiled HTML.

**Comment by jessemiller** [comment]
I think this should be fixed now. Let me know if not...
