### ISSUE TITLE
No way to use django variables in the attrubute consitently.

### ISSUE THREAD

**Issue by svetlyak40wt** [jessemiller/HamlPy#13]
For example, I can't write:

```
#blah{'class': minor}
```

Which compiles to:

```
<div id="blah" class="{{ minor }}"></div>
```

However I could write:

```
#blah{'class': '{{ minor }}'}
```

But this is inconsistent.

**Comment by dmclain** [comment]
I had a commit (0e53ea28782f855107e627a24c3b06f6417f7844) that allowed 
    `#blah{'class':=minor}`
which would then be converted into 
    `#blah{'class':'{{minor}}'}`
and then into
    `<div id="blah" class="{{minor}}">`

It was just a simplistic find and replace, so it led to issues with code like 
    `%a{"href":"{% url foo.bar param=object.value %}"}`

The underlying issue in the codebase is that the attribute dictionary is parsed as a python dictionary by calling eval on the string. While that is very powerful and allows for a lot of complexity, it makes it difficult to change the parsing of the string. My commit used a simple regular expression to find variables prefixed with = to convert, but that's really not a robust approach.

To implement a better way of specifying django variables the parsing of attributes would need to either be handled by using lower level python parsing than eval (http://docs.python.org/library/parser.html) or rolling a parser for just attributes. Both are a lot of work for what amounts to a smarter way to add '{{  }}' around variables, but a cynic could describe HAML as just a lot of work for what amounts to a smarter way to add closing tags.

**Comment by gon** [comment]
What is the right way to write this?

```
%img{'src':item.product.images.0.link}
```

**Comment by dmclain** [comment]
`%img{'src':'{{item.product.images.0.link}}'}` will work

**Comment by gon** [comment]
Yes that works! Thank you.

**Comment by svetlyak40wt** [comment]
OMG
