### ISSUE TITLE
No HTML DOCTYPE?

### ISSUE THREAD

**Issue by ndjdev** [jessemiller/HamlPy#14]
I may be blind here but I can't find anywhere in the docs or code about how to specify the HTML doctype. Will this be added soon?

**Comment by stchris** [comment]
You can simply write
  <doctype HTML>
and it will appear just like that, without further processing.

**Comment by jessemiller** [comment]
There is now:

You can specify a specific doctype after the !!! The following doctypes are supported:

!!!: XHTML 1.0 Transitional
!!! Strict: XHTML 1.0 Strict
!!! Frameset: XHTML 1.0 Frameset
!!! 5: XHTML 5
!!! 1.1: XHTML 1.1
