### ISSUE TITLE
Can't find templatize

### ISSUE THREAD

**Issue by natecox** [jessemiller/HamlPy#156]
I'm attempting to get hamlpy running on Django 1.7/Python 3.3.2 and can't seem to get the template loaders properly configured. I'm curious as to if HamlPy simply won't run under Python 3 or if I have something improperly configured. Note, I am running HamlPy from the repo, not PyPI.

When I attempt to include HamlPy I see the following error: 

```
Error importing module hamlpy.template.loaders: "No module named 'templatize'"
```

Which is confusing, because it's definitely there. My template loader looks like:

```
TEMPLATE_LOADERS = (
    'hamlpy.template.loaders.HamlPyFilesystemLoader',
    'hamlpy.template.loaders.HamlPyAppDirectoriesLoader',
)
```

**Comment by cdimoulis** [comment]
Same problem here. Using Django 1.6. Any solutions?

**Comment by ghost** [comment]
Hi!! 
I solved the problem. Add this code to TEMPLATE_LOADERS `'django.template.loaders.app_directories.Loader',`  

Link info:
[Django-Templates](https://docs.djangoproject.com/en/1.6/ref/templates/api/)
Visit my company
[Webdefamily](https://www.webdefamily.com)
