### ISSUE TITLE
Nested if with else does not close parent if

### ISSUE THREAD

**Issue by mvogel** [jessemiller/HamlPy#21]
I believe this is a regression from the commit:
"fixing nesting of if and for with else. Addresses https://github.com/jessemiller/HamlPy/issues#issue/5"
https://github.com/jessemiller/HamlPy/commit/f0ab3a61e3fff24f8a304ff036a8083042a4b26f

**Comment by dmclain** [comment]
Do you have an example of this behavior? I'm not entirely sure what you mean from the title. A nested if/else shouldn't close the parent if block.

**Comment by mvogel** [comment]
Sorry, what I mean is the nested else does not get closed. Example:

hamlpy:
    - if condition
        -if condition
        -else
    -else

html:
    {% if condition %}
        {% if condition %}
        {% else %}
    ---endif needed here.
    {% else %}
    {% endif %}

**Comment by jessemiller** [comment]
Fixing &#39;Nested if with else does not close parent if&#39; (Closed by f94546fcfc2da862a8bbe4a7700c8bbfd3b35a1a) and tweaking whitespace inside filters
