### ISSUE TITLE
hamlpy crashes when parsing reference.md

### ISSUE THREAD

**Issue by keenbrowne** [jessemiller/HamlPy#23]
running the command:
    hamlpy reference.md 
crashes in elements.py at line 67:
    #attribute_dict_string = re.sub(r'=(?P<variable>[a-zA-Z_][a-zA-Z0-9_.]+)', "'{{\g<variable>}}'", attribute_dict_string)
    attributes_dict = eval(attribute_dict_string)

The following diff makes changes to reference.md so it can be correctly parsed.

```
--- a/reference.md
+++ b/reference.md
@@ -118,7 +118,7 @@ is compiled to:

 These shortcuts can be combined with the attribute dictionary and they will be 

-       %div#Article.article.entry{'id':'1', class='visible'} Booyaka
+       %div#Article.article.entry{'id':'1', 'class': 'visible'} Booyaka

 is equivalent to:

@@ -237,7 +237,7 @@ is compiled to:
 A Django variable can also be used as content for any HTML element by placing a

    %h2
-               %a{'href'='stories/1'}= story.teaser
+               %a{'href': 'stories/1'}= story.teaser

 is compiled to:
```

**Comment by dmclain** [comment]
I apologize for the multiple code attachments. Apparently I don't understand git as well as I need to, after a series of commits, merges and rebases it had the most recent 20 or so commits multiple times. I finally got it figured out (I hope), but it resulted in some stuff hitting github that is now no longer real (or at least no longer in my master branch).
