### ISSUE TITLE
disappeared from PyPI

### ISSUE THREAD

**Issue by emirotin** [jessemiller/HamlPy#29]
```
pip install hamlpy 
```

fails with 

```
Could not find any downloads that satisfy the requirement hamlpy
```

Worked it around by installing directly from github, but would prefer having it installed in a normal way

**Comment by jessemiller** [comment]
I'm not sure why this would be happening. I see it here:
http://pypi.python.org/pypi/hamlpy/0.2

Are you still having an issue?

**Comment by emirotin** [comment]
Yes, still an issue, see the whole log: http://pastebin.com/tt5U46pd

**Comment by jessemiller** [comment]
Ah, got it now. Sorry about that. It should be fixed. Thanks for the additional info. I'll wait to close this when you verifiy.

**Comment by emirotin** [comment]
yes, fixed now
