### ISSUE TITLE
how to use trans in attributes

### ISSUE THREAD

**Issue by qnub** [jessemiller/HamlPy#39]
I need to inser localized value into input field

``` haml
%input{'name':'text', 'type':'text', 'value':'localized_value'}
```

need to be like

``` haml
%input{'name':'text', 'type':'text', 'value':'
  - trans
    Введите значение'}
```

How can i do that?

**Comment by neoascetic** [comment]
It is similar with [#38](https://github.com/jessemiller/HamlPy/issues/38)
Currently I'm use logic in attributes like this:

``` python
%input{'name':'text', 'type':'text', 'value':'{% trans "Введите значение" %}'}
```

just like _raw_ `django template` strings. But, again, we need more haml-way to use attributes.

**Comment by culebron** [comment]
I use HamlPy on a real project, and too often have to fall back to HTML&Django syntax for the issues like this.

I think such syntax can fit haml:

```
%tagname{'attrname': - trans 'my text', 'another_attribute': = variable, = dynamic_attr_name: 'static value', = dynamic_name: = dynamic value}
```

I'm not sure if it's easy to read though.

**Comment by andreif** [comment]
A more [hamlish](http://haml-lang.com/docs/yardoc/file.HAML_REFERENCE.html) way would be

``` haml
%tagname{attrname: trans('my text'), another_attribute: variable, dynamic_attr_name => 'static value', dynamic_name => dynamic value}
```

Note, that HamlPy already supports

``` haml
%tagname{attrname: 'my text'}
```

**Comment by bcoughlan** [comment]
Closing this as it's a duplicate to #38
