### ISSUE TITLE
Haml trans and blocktrans tags are ignored by make_messages utility

### ISSUE THREAD

**Issue by culebron** [jessemiller/HamlPy#40]
I've converted my project to HamlPy and Djaml, and everything works fine except the i18n.

```
%b
    - trans 'Some message text'
```

This `trans` tag is ignored by make_messages command, as well as `blocktrans` in haml syntax. After running `manage.py make_messages` I found all the messages from templates commented out as they were not found.

I know I can fall back to usual syntax like

```
%b {% trans 'Some message text' %}
```

but it undoes a lot of gains of haml. Is there a way to make the translation parser recognize haml syntax?

**Comment by culebron** [comment]
in the pull request #42, I've added a fix to this: haml templates are processed on the fly. Still, you need to import hamlpy explicitly from your project to make it decorate the templatize function. I'm not sure how to plug it into django automatically.

**Comment by jessemiller** [comment]
Thanks for the commit!
