### ISSUE TITLE
Inconsistency: custom template tags have to be closed manually

### ISSUE THREAD

**Issue by culebron** [jessemiller/HamlPy#41]
Just a couple of examples.

Works:

```
#content.partial_update.page.oldSchool
    - block content
        %h1 En el bar has encontrado a tus conocidos juntos. Están alegres y te dicen que van a casarse entre un mes.
```

But:

```
- blocktrans with object.duration_as_time as dur
    %span.jtimer.bigger {{ dur }}
    remain
- endblocktrans
```

I have to close `blocktrans` manually.

What can be done to make it work automatically?

**Comment by andreif** [comment]
+1
The code is in [`hamlpy.nodes.TagNode`](https://github.com/jessemiller/HamlPy/blob/master/hamlpy/nodes.py#L223), but I have no idea how to make it auto yet.
