### ISSUE TITLE
Apostrophes in attributes are escaped (prevents developer from using url tag)

### ISSUE THREAD

**Issue by bcoughlan** [jessemiller/HamlPy#50]
`action: "{% url 'django.contrib.auth.views.login' %}"`

renders as:

`action='{% url &quot;django.contrib.auth.views.login&quot; %}'``

Which is obviously problematic. Had a poke around the code but I'm not familiar enough with it yet to track down the problem.

Is there a need to escape apostrpohes at all. Given that it's a developers language I don't see any security risk posed by it.

**Comment by andreif** [comment]
I think this issue is related to [#38](https://github.com/jessemiller/HamlPy/issues/38) and [#39](https://github.com/jessemiller/HamlPy/issues/39). Using logic as a string with Django template tags is probably not the best idea. I believe we can add some original haml logic:

``` haml
%form{action: url('django.contrib.auth.views.login')}
```

converted to:

``` html
<form action="{% url 'django.contrib.auth.views.login' %}">
```

**Comment by andreif** [comment]
You may be also interested in https://github.com/albsen/HamlPy/pull/4#issuecomment-2180388
