### ISSUE TITLE
Django variables with plain text are not evaluated

### ISSUE THREAD

**Issue by helmutgranda** [jessemiller/HamlPy#54]
Accordingly to the documentation:

"A Django variable can also be used as content for any HTML element by placing an equals sign as the last character before the space and content"

it works great with tags but how about plain text?

``` python
- block heading
    Title=django_variable
```

result:

``` python
<% block heading %>
Title=django_variable
<% endblock %>
```

**Comment by jessemiller** [comment]
I think what you'd like to do there is go:

```
- block heading
    %title= django_variable
```

Which would output:

```
<% block heading %>
  <title>{{ django_variable }}</title>
<% endblock %>
```

**Comment by helmutgranda** [comment]
My example was kind of confusing by me using the the keyword "title" but I do see what you are saying.

Here is another live example:

Written

``` python
%li{tooltip:'= thumbnail_name'}
```

Result

``` python
<li tooltip='= thumbnail_name'>
```

Solution

``` python
%li{tooltip:'{{ thumbnail.name}}'}
```

**Comment by md3sum** [comment]
@helmutgranda : Are you referring to the "Ruby Blocks" section in the HAML documentation : http://haml-lang.com/docs/yardoc/file.HAML_REFERENCE.html#ruby_blocks

If so, I agree, that variables should also evaluate itself.

**Comment by bcoughlan** [comment]
Submitting a fix for this. Because of the conflict with attributes that can also have equals signs inside (e.g. the type attribute in HTML5 Video has "codec=..." inside of it), this fix only recognises attributes where the whole string is a variable, i.e.`a="= somevar"` but not `a="something = somevar"`
