### ISSUE TITLE
Tabs converted to only 1 space

### ISSUE THREAD

**Issue by helmutgranda** [jessemiller/HamlPy#55]
When parsed tabs are converted to 1 space rather than a full tab in HTML. Maybe there is a setting but have not been able to locate it so answer things question may help others that run into this issue.

**Comment by bcoughlan** [comment]
nodes.py Line 122:

```
        self.indentation = (len(haml) - len(haml.lstrip()))
        self.spaces = ''.join(' ' for i in range(self.indentation))
```

You'll see that hamlpy replaces all tabs with spaces. The easy fix is just to change `' '` to `'\t'`. I've gone a step further and changed it to be haml[0](i.e. whatever the first character they entered is) and it seems to work fine.

I generally set my IDE to convert tabs to spaces to avoid the problem of mixed tabs and spaces.
