### ISSUE TITLE
Add self-closing support for custom template tags

### ISSUE THREAD

**Issue by hijonathan** [jessemiller/HamlPy#56]
Example:

```
- mytag
      Add stuff here
```

compiles to:

```
{% mytag %}
      Add stuff here
{% endmytag %}
```

It'd be nice to support these and just assume/require that we adhere to typical django naming conventions (e.g. the closing tag starts with "end").

**Comment by bcoughlan** [comment]
Are there any scenarios where a tag followed by an indented line shouldn't be self-closing?

**Comment by hijonathan** [comment]
Yeah, actually this would be a problem for custom one-liner tags.

Example:

```
- wrap_in_anchor "http://www.example.com"
```

should compile to:

```
{% wrap_in_anchor "http://www.example.com" %}
```

which could then be used to wrap the passed value in a special anchor tag or whatever.

I think there may be a better way to do this, but I haven't quite figured it out yet.
