### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by ghost** [jessemiller/HamlPy#6]
Is there a way to include Javascript on the page? I tried to use the :javascript syntax from Haml, but no luck.

**Comment by stchris** [comment]
I think for now you could just write a simple <script> tag into your hamlpy file. The :javascript part of haml is actually a filter, for which there is not support (yet?) in HamlPy.

**Comment by jessemiller** [comment]
Yes, no support for filters yet. I'd like to add it though.  The :javascript filter would probably be the first one to tackle.  I'll take a look at this soon.

**Comment by ghost** [comment]
Thank you, both. I'll use the tag for now.
