### ISSUE TITLE
hamlpy-watcher compatibility with emacs

### ISSUE THREAD

**Issue by ldpl** [jessemiller/HamlPy#61]
While editing emacs for some reason creates broken symlinks like .#base.haml -> user@comp.18892:1224901752
Hamlpy-watcher do not provide any way to ignore them and fails with traceback when it tries to convert them.

**Comment by bcoughlan** [comment]
Can you post the traceback and any other details

**Comment by ldpl** [comment]
Sure. Steps to reproduce:
1. $ mkdir t
2. $ touch t/index.haml
3. $ hamlpy-watcher t
Watching /home/pavels/Builds/hp/HamlPy/t at refresh interval 3 seconds
21:54:10 /home/pavels/Builds/hp/HamlPy/t/index.haml -> /home/pavels/Builds/hp/HamlPy/t/./index.html
4. start editing t/index.haml in emacs, but do not save it
5. In console with hamlpy-watcher:
Traceback (most recent call last):
  File "/usr/bin/hamlpy-watcher", line 9, in <module>
    load_entry_point('hamlpy==0.4', 'console_scripts', 'hamlpy-watcher')()
  File "/usr/lib/python2.7/site-packages/hamlpy-0.4-py2.7.egg/hamlpy/hamlpy_watcher.py", line 38, in watch_folder
    _watch_folder(folder, destination)
  File "/usr/lib/python2.7/site-packages/hamlpy-0.4-py2.7.egg/hamlpy/hamlpy_watcher.py", line 55, in _watch_folder
    mtime = os.stat(fullpath).st_mtime
OSError: [Errno 2] No such file or directory: '/home/pavels/Builds/hp/HamlPy/t/.#index.haml'
6. $ ls -lsa t
total 12
4 drwxrwxr-x 2 pavels pavels 4096 Jan  6 01:55 .
4 drwxr-xr-x 8 pavels pavels 4096 Jan  6 01:53 ..
0 lrwxrwxrwx 1 pavels pavels   28 Jan  6 01:54 .#index.haml -> pavels@dbook.2734:1325754064
4 -rw-rw-r-- 1 pavels pavels    4 Jan  6 01:55 #index.haml#
0 -rw-rw-r-- 1 pavels pavels    0 Jan  6 01:53 index.haml
0 -rw-rw-r-- 1 pavels pavels    0 Jan  6 01:54 index.html
