### ISSUE TITLE
Cannot install with pip

### ISSUE THREAD

**Issue by ghost** [jessemiller/HamlPy#64]
Not sure if this is HamlPy's problem or if it's pip's problem. at any rate, it looks like pip tries to install the Mac OS version, and then fails because it can't find setup.py. I'm running Fedora 15. Here's the relevant error:

```
$ pip install hamlpy
Downloading/unpacking hamlpy
  Downloading hamlpy-0.6.macosx-10.7-intel.tar.gz
  Running setup.py egg_info for package hamlpy
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '[VE]/build/hamlpy/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>


IOError: [Errno 2] No such file or directory: '[VE]/build/hamlpy/setup.py'
```

**Comment by quekshuy** [comment]
I faced the same problem. I worked around this using the following method (I'm using virtualenv by the way):
1. Cloned the repository into [virtualenv_dir]/tmp/hamlpy
2. In [virtualenv_dir]/bin created a script **hamlpy-watcher** with the following content
   
   ```
        python [virtualenv_dir]/tmp/hamlpy/hamlpy/hamlpy_watcher.py $1
   ```
3. Ran 
   
   ```
        chmod u+x hamlpy-watcher
   ```

**Comment by bcoughlan** [comment]
Can confirm I'm getting the same problem under Windows (it's trying to install the Mac version). 

Must be some issue related to the last push to pypi: http://pypi.python.org/simple/hamlpy/ pip finds 0.6 to be the latest, but that package doesn't appear to have been zipped correctly.

**Comment by andreif** [comment]
I had a problem to install HamlPy on Mac OS X. This worked though: `pip install git+git://github.com/jessemiller/HamlPy.git`

The traceback of `pip install hamlpy`:

```
Downloading/unpacking hamlpy (from -r requirements.pip (line 5))
  Downloading hamlpy-0.6.macosx-10.7-intel.tar.gz
  Running setup.py egg_info for package hamlpy
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/Users/andrei/.pythonbrew/venvs/Python-2.7.2/abc/build/hamlpy/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/Users/andrei/.pythonbrew/venvs/Python-2.7.2/abc/build/hamlpy/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1
```

**Comment by Ins1ne** [comment]
Can confirm this issue.
Trying install via <code>easy_install hamlpy</code>:

<pre>
Searching for hamlpy
Reading http://pypi.python.org/simple/hamlpy/
Reading http://github.com/jessemiller/HamlPy
Reading http://pypi.python.org/simple/hamlpy/git@github.com:jessemiller/HamlPy.git
Best match: hamlpy 0.6.macosx-10.7-intel
Downloading http://pypi.python.org/packages/any/h/hamlpy/hamlpy-0.6.macosx-10.7-intel.tar.gz#md5=141dc2de65949d92c989c65eb96a780d
Processing hamlpy-0.6.macosx-10.7-intel.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-kSuQP2/hamlpy-0.6.macosx-10.7-intel.tar.gz
</pre>

**Comment by modocache** [comment]
I'm having the same problem.

```
@modocache ~/$ pip install hamlpy
Downloading/unpacking hamlpy
  Downloading hamlpy-0.6.macosx-10.7-intel.tar.gz
  Running setup.py egg_info for package hamlpy
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/Users/modocache/.virtualenvs/dg/build/hamlpy/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/Users/modocache/.virtualenvs/dg/build/hamlpy/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /Users/modocache/.pip/pip.log
```

I ran `pip install git+...` like @andreif did, so I guess it's not too big a deal.

**Comment by jessemiller** [comment]
This should be fixed now.. really sorry about it.. can someone else confirm?

**Comment by ghost** [comment]
Hamlpy now installs correctly for me.

**Comment by modocache** [comment]
Awesome, fixed for me, too. Thanks!
