### ISSUE TITLE
Filter indentation gets screwed up when nested

### ISSUE THREAD

**Issue by hijonathan** [jessemiller/HamlPy#67]
This:

```
%head
  :javascript
    $(document).ready(function(){
      $("#form{{form.initial.id}}").submit(form_submit);
      // Javascript comment
    });
  :css
    .someClass {
      width: 100px;
    }
  :cdata
    if (a < b && a < 0)
    {
      return 1;
    }
```

should compile to this:

```
<head>
  <script type='text/javascript'>
  // <![CDATA[
    $(document).ready(function(){
      $("#form{{form.initial.id}}").submit(form_submit);
      // Javascript comment
    });
  // ]]>
  </script>
  <style type='text/css'>
  /*<![CDATA[*/
    .someClass {
      width: 100px;
    }
  /*]]>*/
  </style>
  <![CDATA[
    if (a < b && a < 0)
    {
      return 1;
    }
  ]]>
<head>
```

but instead, it compiles to this:

```
<head>
<script type='text/javascript'>
// <![CDATA[
    $(document).ready(function(){      $("#form{{form.initial.id}}").submit(form_submit);      // Javascript comment    });
// ]]>
</script>
<style type='text/css'>
/*<![CDATA[*/
    .someClass {      width: 100px;    }
/*]]>*/
</style>
  <![CDATA[
    if (a < b && a < 0)
    {      return 1;    }
  ]]>
</head>
```

**Comment by bcoughlan** [comment]
I came across this yesterday also, and it may have something to do with a previous issue (#52), which fixed multi-line HAML that contained other braces within it.

The code was supposed to ignore any data picked up in js/css/plaintext nodes

Oddly enough, I created a test (filterMultilineIgnore.haml and filterMultilineIgnore.html) to test for this, but must have overlooked something.

Having a busy week but will revisit this as soon as I can.

**Comment by hijonathan** [comment]
Thanks! I'll try to send a pull request if I find some time this weekend.

**Comment by bcoughlan** [comment]
The problem was that the code for checking the node type of an element's parent wasn't working in hamlpy.py.

Wrote a parent() function in RootNode) which gets the parent of an element (like add_node, only works while parsing, and added some tests.
