### ISSUE TITLE
Whitespace Removal via > and < possible?

### ISSUE THREAD

**Issue by harryfk** [jessemiller/HamlPy#71]
Hey there,
first of all: Thank you for your effort in bringing HAML to the Python world. I’m coming from a Ruby background and your implementation makes me feel at home. :)
I’ve a quick question – in the original HAML there is the possibility to control whitespace output.

[See the HAML-Documentation about Whitespace](http://haml-lang.com/docs/yardoc/file.HAML_REFERENCE.html#whitespace_removal__and_)

I’m wondering if something similar exists in your implementation … the feature is especially important when it comes to inline-blocks because they are whitespace-aware and I need an output without any whitespace between them.

Any help on the matter would be greatly appreciated. :)

Best regards,
Harry

**Comment by bcoughlan** [comment]
There's no feature in HamlPy to do this that I'm aware of. It's the first time I've come across it (and seems like a where-have-you-been-all-my-life feature!)

I'm quite busy myself over the next few weeks but if I find time I'll have a go at implementing it. You're welcome to do so yourself of course, just let me know so that we don't end up working on the same thing.

**Comment by harryfk** [comment]
Hey again and thanks for the quick reply. As much as I want to help you, the coming weeks are pretty busy for me as well and I won’t have the time to look into it. I found a solution for the meantime though:

Just in case anyone else is struggling with this in Django … I found out you can achieve similar output by using a spaceless block: https://docs.djangoproject.com/en/1.3/ref/templates/builtins/#spaceless

Still, the < and > operators in HAML allow more fine-grained control – but the spaceless block will do just fine until you can find the time to implement it. No rush. Thanks again for your effort!

**Comment by bcoughlan** [comment]
That should do it.
