### ISSUE TITLE
watcher script

### ISSUE THREAD

**Issue by stchris** [jessemiller/HamlPy#8]
First of all: thanks for your work! This is really great!

Do you plan to add a watcher script, such that changed files with the .hamlpy extension get automatically compiled? I was thinking of writing it myself, but I'm not sure if polling would be better than inotify (cross-platform vs. performance). Also, fssm would be an option (http://chriseppstein.github.com/blog/2009/09/07/building-a-jekyll-watcher-with-fssm/), but then again... that's ruby code in a python project...

**Comment by jessemiller** [comment]
A watcher script might work great for it.  I have a watcher script in the project already for doing an autotest type thing.  Not sure how people feel about ruby in a python project, but I guess if it's already written they can't complain too much :)

Let me know if you get one put together.

**Comment by stchris** [comment]
See #11
