### ISSUE TITLE
Set 'img src' with template variable

### ISSUE THREAD

**Issue by ghost** [jessemiller/HamlPy#80]
would like to set an image's source attribute like this:

``` haml
%img {'src': '= item.thumbnail'}
```

but I ended up doing this:

``` haml
:python
  print "<img src='{{ item.thumbnail }}' />"
```

I'm not sure if I am doing it wrong or HamPy is doing it wrong. If if turns out this is a bug, I'm happy to step in and fix it, but it could very well be an error on my part.

**Comment by bcoughlan** [comment]
Related to this (periods in attribute values)? https://github.com/jessemiller/HamlPy/pull/77
You may just have to update your repository.

(On another node, the :python is unnecessary here, you can just write the plain text)

**Comment by ghost** [comment]
Thank you. Also, I was using the :python filter out of confusion, in some places I was using :python to print a string and then = template_variable, instead of just {{ template_variable }}. 

I will update my repo, thanks!
