### ISSUE TITLE
Bug?: translating attributes that are made of objects properties

### ISSUE THREAD

**Issue by martar** [jessemiller/HamlPy#85]
I encounter a fallowing bug:
parcing the line  (taking properties of the variable 'user'):
            %i.icon-user{'id': 'UserInfo','data-is-staff': '= user.is_stuff', 'data-id':'= user.pk'}
results in 
            <i id='UserInfo' class='icon-user' data-id='= user.pk' data-is-staff='= user.is_stuff'></i>

in order to have it worked propetly i made a workaround:
    - with user_is_stuff=user.is_stauff user_pk=user.pk
              %i.icon-user{'id': 'UserInfo','data-is-staff': '= user_is_stuff', 'data-id':'= user_pk'}

that results in right output:
            {% with user_is_stuff=user.is_stauff user_pk=user.pk %}
              <i id='UserInfo' class='icon-user' data-id='{{user_pk}}' data-is-staff='{{user_is_stuff}}'></i>
            {% endwith %}

**Comment by bcoughlan** [comment]
Hi martar,

This was fixed in #77 a few months ago, so just update your version of HamlPy

Regards,
Barry

**Comment by martar** [comment]
ok thanks, it works with the repo version of hamlPy. Version on easy_install is old
