### ISSUE TITLE
document inline variable usage on reference page

### ISSUE THREAD

**Issue by dillongreen** [jessemiller/HamlPy#87]
https://github.com/jessemiller/HamlPy/blob/master/reference.md should show an example for inline variable usage as otherwise folks would need to literally write

```
Hello
= user.name
,how are you today?
```

instead of just `Hello #{user.name}, how are you today?`

Inline variables were added about two years ago with https://github.com/jessemiller/HamlPy/pull/17

**Comment by jessemiller** [comment]
Fixed. You are welcome to do a pull request next time :)

**Comment by dillongreen** [comment]
Cheers, will do ;)
