### ISSUE TITLE
Javascript linebreaks disappear after ( {

### ISSUE THREAD

**Issue by culebron** [jessemiller/HamlPy#90]
I've found a bug that destroys Javascript linebreaks.

Here's the bug in a simple form. The first :javascript becomes broken, the second does not.

```
:javascript
        (
            {
                a
            }
        );


:javascript

            {
                a
            }
        )
```

Here's the output:

```
<script type='text/javascript'>
// <![CDATA[
        (
            {                a            }
        );
// ]]>
</script>
<script type='text/javascript'>
// <![CDATA[
            {
                a
            }
        )
// ]]>
</script>
```

Here's a template that has the bug too: http://pastebin.com/ZDfjF6ed

**Comment by bcoughlan** [comment]
Fixed and pushed to master. Jesse if you see this the PyPi version is getting a little out of date :)

**Comment by jessemiller** [comment]
Cool.. I'll deploy a version today. Thanks!
