### ISSUE TITLE
PyPi lists v0.81.2, but only 0.80.4 is downloaded by setuptools

### ISSUE THREAD

**Issue by culebron** [jessemiller/HamlPy#91]
I don't know if this is PyPI's issue or there was an error while uploading the package, but I can't run buildout with hamlpy version 0.81.2:

Getting distribution for 'hamlpy>=0.81'.
While:
  Installing django.
  Getting distribution for 'hamlpy>=0.81'.
Error: Couldn't find a distribution for 'hamlpy>=0.81'.

**Comment by jessemiller** [comment]
Sorry about that. It should be fixed now.

**Comment by culebron** [comment]
Thanks!
