### ISSUE TITLE
AttributeError: 'ElementNode' object has no attribute 'element' 

### ISSUE THREAD

**Issue by altimore** [jessemiller/HamlPy#92]
Hello, 

In some case the Element node have no attribute element (in comments it seems), so the function crash when trying to call self.element in : hamlpy/nodes.py", line 282, in _post_render

To reproduce :

Write this in a file : test.haml

```
-# My comment
    #my_div
        my text
```

then execute hamlpy test.haml

**Comment by bcoughlan** [comment]
Thanks altimore. Fixed in 0.82, (see the readme for how to install the development version)

**Comment by altimore** [comment]
Thanks to you, it was quite fast !
Your solution is much cleaner than the temporary 'try: except:' i put in you _post_render() function !
