### ISSUE TITLE
Missing the template folder with pip install

### ISSUE THREAD

**Issue by altimore** [jessemiller/HamlPy#93]
Hello again !

I followed your instructions and ran `pip install https://github.com/jessemiller/HamlPy/tarball/master` but it depoys only the py files in my virtual env (not the template folder) so i can't use your djaml inclusion.

I think that could be an egg configuration problem.

I confirm it deployed the 0.82 version and the patch from the issue #92 is present.

**Comment by imxxb** [comment]
same issue version 0.81.3
