### ISSUE TITLE
Update PyPi

### ISSUE THREAD

**Issue by bcoughlan** [jessemiller/HamlPy#95]
Hey Jesse, could you roll version and update PyPi again? Template loader isn't included in the current release (fixed in #94)

**Comment by evanreiser** [comment]
Agreed.

For future people looking at this you may be seing this error: "Error importing template source loader hamlpy.template.loaders.HamlPyFilesystemLoader: "No module named template.loaders""

**Comment by bcoughlan** [comment]
Until it's updated: See the readme for how to get the development version from pip.

If you're using virtualenv for something like Heroku and need hamlpy, you can tell it to grab the latest dev version by putting `git+git://github.com/jessemiller/HamlPy.git` in your requirements.txt

**Comment by jessemiller** [comment]
Updated now. Sorry for the delay, I was in Mexico.

**Comment by evanreiser** [comment]
Awesome, thank you!

**Comment by bcoughlan** [comment]
That's a good enough reason ;)
