### ISSUE TITLE
Problems doing pip install

### ISSUE THREAD

**Issue by hijonathan** [jessemiller/HamlPy#98]
Seems to install fine if you run `pip install hamlpy` but not if it's a dependency listed in another package's setup.py/requirements.pip file.

I saw [a line note](https://github.com/jessemiller/HamlPy/blob/master/setup.py#L3) about pushing via `sdist` instead of `bdist`. Any chance that 0.82.2 was pushed incorrectly?

**Comment by bcoughlan** [comment]
If you need a workaround in the meantime you can put `git+git://github.com/jessemiller/HamlPy.git` as a line in requirements.txt to pull directly from Github

**Comment by hijonathan** [comment]
Hm... I'll just add some helper script or put instructions to install hamlpy first. Not a huge deal.
